spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/diancan?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /**
  redis:
    host: 192.168.217.128
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
  appid: wx940c29bd5e0c0cc1
#  appid: wx295cbc0caa647a18

  secret: 754d9a39a682c0433cf25b8cd7d9933c
#  secret: 765831a9b97bee46f7d1b03efbbb3ec3
  returnUrl: http://a714bbd8.ngrok.io/sell/wechat/userInfo
  token: myo2o
mybatis:
  type-aliases-package: com.lq.sell.dataobject


